name: publish
on:
    push:
        branches:
            - main
    schedule:
        # Run daily at 1 AM UTC
        - cron: "0 1 * * *"
    workflow_dispatch: # Allow manual triggering
permissions:
    contents: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Configure Git Credentials
              run: |
                  git config user.name github-actions[bot]
                  git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.x
            - name: Install uv
              uses: astral-sh/setup-uv@v3
            - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
            - uses: actions/cache@v4
              with:
                  key: mkdocs-material-${{ env.cache_id }}
                  path: .cache
                  restore-keys: |
                      mkdocs-material-
            - run: uv sync
            - run: uv run mkdocs gh-deploy --force
